// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgjjrtD-xah4RRBOk0_C1hR8oSFvRXXgc',
    appId: '1:145757475794:web:8fe948cb4db56df83eee0b',
    messagingSenderId: '145757475794',
    projectId: 'apple-notes-meow',
    authDomain: 'apple-notes-meow.firebaseapp.com',
    storageBucket: 'apple-notes-meow.firebasestorage.app',
    measurementId: 'G-747PEN6ZPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVEZi_KyOR409V-z3XMOTS3Bh7nMDr1aA',
    appId: '1:145757475794:android:954158357ea95af23eee0b',
    messagingSenderId: '145757475794',
    projectId: 'apple-notes-meow',
    storageBucket: 'apple-notes-meow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW1YmNwBIZ2dLhQ76gIQK3yUhr9LcNy04',
    appId: '1:145757475794:ios:a875cece278b1c963eee0b',
    messagingSenderId: '145757475794',
    projectId: 'apple-notes-meow',
    storageBucket: 'apple-notes-meow.firebasestorage.app',
    iosBundleId: 'meow.psps.appleNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW1YmNwBIZ2dLhQ76gIQK3yUhr9LcNy04',
    appId: '1:145757475794:ios:a875cece278b1c963eee0b',
    messagingSenderId: '145757475794',
    projectId: 'apple-notes-meow',
    storageBucket: 'apple-notes-meow.firebasestorage.app',
    iosBundleId: 'meow.psps.appleNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgjjrtD-xah4RRBOk0_C1hR8oSFvRXXgc',
    appId: '1:145757475794:web:04a302e53d7f6e8a3eee0b',
    messagingSenderId: '145757475794',
    projectId: 'apple-notes-meow',
    authDomain: 'apple-notes-meow.firebaseapp.com',
    storageBucket: 'apple-notes-meow.firebasestorage.app',
    measurementId: 'G-VQW52CHWRK',
  );
}
